### ISSUE TITLE
dom解析慢的问题

### ISSUE THREAD

**Issue by mgljava** [QuSongtao/demo-pdf#1]
楼主你好：
  我在使用你这个开源项目的时候遇到了一个问题，就是我的ftl文件非常大，用你的Dom解析很慢，需要几十秒钟。您的代码如下：
`/**
   * 按模板和参数生成html字符串,再转换为flying-saucer识别的Document
   *
   * @param templateName freemarker模板名称
   * @param variables freemarker模板参数
   * @return Document
   */
  private static Document generateDoc(FreeMarkerConfigurer configurer, String templateName,
      Map<String, Object> variables) {
    Template tp;
    try {
      tp = configurer.getConfiguration().getTemplate(templateName);
    } catch (IOException e) {
      LOGGER.error(e.getMessage(), e);
      return null;
    }
    StringWriter stringWriter = new StringWriter();
    try (BufferedWriter writer = new BufferedWriter(stringWriter)) {
      try {
        tp.process(variables, writer);
        writer.flush();
      } catch (TemplateException e) {
        LOGGER.error("模板不存在或者路径错误", e);
      } catch (IOException e) {
        LOGGER.error("IO异常", e);
      }
      DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
      return builder.parse(new ByteArrayInputStream(stringWriter.toString().getBytes()));
    } catch (Exception e) {
      LOGGER.error(e.getMessage(), e);
      return null;
    }
  }`
调用方式：
    `Document doc = generateDoc(configurer, templateName, map);
    renderer.setDocument(doc, null);`  
-----------------------我改用了如下方式---------------------
`StringWriter writer = new StringWriter();
    Template template = configurer.getConfiguration().getTemplate(templateName);
    template.process(map, writer);
    writer.flush();
    String html = writer.toString();
    renderer.setDocumentFromString(html);`
解析时间缩短至 ms 级别。

**Comment by QuSongtao** [comment]
好啊,多谢改进,同时也需要验证一下兼容性
